version: '3.9'

services:
  postgres_liquibase:
    image: postgres:latest
    container_name: postgres-liquibase
    environment:
      POSTGRES_USER: rob
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_databse
    volumes:
      - pg_liqui_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase-runner
    depends_on:
      - postgres_liquibase
    volumes:
      - ./drivers:/drivers
      - ./master-changelog.xml:/liquibase-host/master-changelog.xml
      - ./liquibase.properties:/liquibase-host/liquibase.properties
      - ./rob:/liquibase-host/rob
      - ./sarah:/liquibase-host/sarah
    command: >
      --changeLogFile=/liquibase-host/master-changelog.xml
      --defaultsFile=/liquibase-host/liquibase.properties
      update

volumes:
  pg_liqui_data: