version: '3.9'

services:
  postgres_liquibase:
    image: postgres:latest
    container_name: postgres-liquibase
    environment:
      POSTGRES_USER: rob
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_databse
    volumes:
      - pg_liqui_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pg_liqui_data: